apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "validator.fullname" . }}
  labels:
  {{- include "validator.labels" . | nindent 4 }}
# Use --include-dir when this PR is released (prob. Helm 3.4.0):
#  https://github.com/helm/helm/pull/8227
data:
  keymanageropts.json: |-
    {
      "direct_eip_version": "EIP-2335",
      "direct_accounts_passwords_directory": "/home/.eth2validators/prysm-wallet-v2-passwords"
    }
  {{- (.Files.Glob "config/wallet/*").AsConfig | nindent 2 }}