apiVersion: v1
kind: Service
metadata:
  name: {{ include "validator.fullname" . }}-metrics
  labels:
  {{- include "validator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.ports.metrics }}
      targetPort: {{ .Values.ports.metrics }}
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/name: {{ include "validator.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}