apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "beacon-node.fullname" . }}
  labels:
    {{- include "beacon-node.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "beacon-node.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "beacon-node.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.beaconNode.image.repository }}:{{ .Values.beaconNode.image.tag }}
          imagePullPolicy: {{ .Values.beaconNode.image.pullPolicy }}
          ports:
            - containerPort: 13000
              protocol: TCP
            - containerPort: 12000
              protocol: UDP
            - name: grpc
              containerPort: 4000
              protocol: TCP
            - name: metrics
              containerPort: {{ .Values.beaconNode.metricsPort }}
              protocol: TCP
{{/*          livenessProbe:*/}}
{{/*            httpGet:*/}}
{{/*              path: /metrics*/}}
{{/*              port: metrics*/}}
{{/*          readinessProbe:*/}}
{{/*            httpGet:*/}}
{{/*              path: /metrics*/}}
{{/*              port: metrics*/}}
