apiVersion: v1
kind: Service
metadata:
  name: {{ include "beacon-node.fullname" . }}-udp
  labels:
  {{- include "beacon-node.labels" . | nindent 4 }}
spec:
  type: {{ .Values.serviceType }}
  ports:
    - port: 12000
      targetPort: 12000
      protocol: UDP
  selector:
    app.kubernetes.io/name: {{ include "beacon-node.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}