apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "beacon-node-data.fullname" . }}
  labels:
  {{- include "beacon-node-data.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: microk8s-hostpath
  resources:
    requests:
      storage: 20Gi