nameOverride: ""
fullnameOverride: ""

prometheus:
  validatorMetricsUrl: prysm-validator-metrics
  defaultMetricsPort: 8080
  persistentStorageSize: 5Gi
  listenPort: 9090
  dataPath: "/prometheus"
  configPath: "/etc/prometheus"

  deployment:
    replicaCount: 1
    podSecurityContext:
      runAsUser: 65534
      runAsGroup: 65534
      fsGroup: 65534
    image:
      repository: "prom/prometheus"
      pullPolicy: Always
      tag: "latest"

    healthEndpoint: "/healthz"
    beaconNode: medalla-prysm-beacon-node-grcp

ports:
  metrics: 8080

volumeClaim:
  storageClassName: microk8s-hostpath
