nameOverride: ""
fullnameOverride: ""

deployment:
  replicaCount: 1
  image:
    repository: "jbarthel/prysm-node"
    pullPolicy: Always
    tag: "latest-arm64"

  configDir: "/config"
  configName: "validator.yaml"

  beaconNode: medalla-prysm-beacon-node-grcp

ports:
  metrics: 8080

wallet:
  keymanagerOptsFileName: "keymanageropts.json"
  accountsFilename: "all-accounts.keystore.json"
  walletDirectory: "/wallet"
  walletPassword: "<pass-as-parameter>"
  walletPasswordPath: "/wallet/wallet-password"
  walletSecretSubPath: "wallet-password"