replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

podAnnotations: {}

nameOverride: ""
fullnameOverride: ""

podSecurityContext:
  runAsUser: 101
  runAsGroup: 101
  fsGroup: 101

nodeSelector: {}

hostKeystoreLocation: ""

walletDirectory: "/wallet"

walletPassword: "<pass-as-parameter>"