replicaCount: 1

image:
  repository: "jbarthel/prysm-node"
  pullPolicy: Always
  tag: "latest-arm64"

metricsPort: 8080
configDir: "/config"
configName: "validator.yaml"


podAnnotations: {}

nameOverride: ""
fullnameOverride: ""

nodeSelector: {}

hostKeystoreLocation: ""

walletDirectory: "/wallet"

walletPassword: "<pass-as-parameter>"

beaconNode: medalla-prysm-beacon-node-grcp