apiVersion: v1
kind: Service
metadata:
  name: {{ include "monitoring.fullname" . }}-grafana
  labels: {{- include "monitoring.grafanaLabels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.grafana.listenPort }}
      targetPort: {{ .Values.grafana.listenPort }}
      protocol: TCP
      name: grafana
  selector:
    {{- include "monitoring.grafanaSelectorLabels" . | nindent 4 }}
