apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "monitoring.fullname" . }}-grafana
  labels: {{- include "monitoring.grafanaLabels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.volumeClaim.storageClassName }}
  storageClassName: {{ .Values.volumeClaim.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.grafana.persistentStorageSize }}
