apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "beacon-node.fullname" . }}
  labels:
  {{- include "beacon-node.labels" . | nindent 4 }}
data:
  beacon.yaml: |-
{{ .Files.Get "config/beacon.yaml" | indent 4 }}