apiVersion: v1
kind: Service
metadata:
  name: {{ include "beacon-node.fullname" . }}-grcp
  labels:
  {{- include "beacon-node.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP
      name: grpc
  selector:
    app.kubernetes.io/name: {{ include "beacon-node.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}