apiVersion: v1
kind: Service
metadata:
  name: {{ include "beacon-node.fullname" . }}-metrics
  labels:
  {{- include "beacon-node.labels" . | nindent 4 }}
spec:
  type: {{ .Values.serviceType }}
  ports:
    - port: {{ .Values.ports.metrics }}
      targetPort: {{ .Values.ports.metrics }}
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/name: {{ include "beacon-node.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}