apiVersion: v1
kind: Service
metadata:
  name: {{ include "beacon-node.fullname" . }}-udp
  labels:
  {{- include "beacon-node.labels" . | nindent 4 }}
spec:
  type: {{ .Values.serviceType }}
  ports:
    - port: {{ .Values.ports.p2pUdp }}
      targetPort: {{ .Values.ports.p2pUdp }}
      protocol: UDP
      name: udp
  selector:
    app.kubernetes.io/name: {{ include "beacon-node.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}