apiVersion: v1
kind: Service
metadata:
  name: {{ include "beacon-node.fullname" . }}-tcp
  labels:
  {{- include "beacon-node.labels" . | nindent 4 }}
spec:
  type: {{ .Values.serviceType }}
  ports:
    - port: 13000
      targetPort: 13000
      protocol: TCP
      name: tcp
  selector:
    app.kubernetes.io/name: {{ include "beacon-node.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}