apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "beacon-node.fullname" . }}-stats
  labels:
  {{- include "beacon-node.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.storageClassName }}
  storageClassName: {{ .Values.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.stats.persistentVolume.size }}
